#!/usr/bin/env php

<?php

// set to run indefinitely if needed
set_time_limit(0);

error_reporting(E_ALL);         // For debugging propose
ini_set('display_errors', 1);   // For debugging propose

// include the composer autoloader
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    fwrite(STDERR, 'ERROR: Composer dependencies not properly set up! Run "composer install" or see README.md for more details' . PHP_EOL);
    exit(1);
}



$application = new \Symfony\Component\Console\Application('Issue exporter', '1.0.0');
$application->add(new \Tjoosten\Github\Issues\Commands\ExportCommand);
$application->run();
